### ISSUE TITLE
User 404 Error, when going to page 2

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#14]
Hi,

```
from phub import Client

model = Client().get_user("https://de.pornhub.com/model/luna-okko")
videos = model.videos
for video in videos:
    print(video.title)
```

I get this error here:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pornhub.com/model/luna-okko/videos?page=2
```

But the first 32 videos were valid with no errors. I guess this is just a simpe error.

I used V4 with the newest commits.

**Comment by Egsagon** [comment]
Hi,

Have you tested with other users/models?
I'm in school rn i can't really open PH pages...

I believe i forgot to add the stop part from PHUB3:
https://github.com/Egsagon/PHUB/blob/8afd68aa7b09ed335ba8b82af860404908ce7c8f/src/phub/classes.py#L582-L585

**Comment by Egsagon** [comment]
Should be fixed in both branches.
