### ISSUE TITLE
The path param is not working correctly

### ISSUE THREAD

**Issue by romanesko** [Egsagon/PHUB#17]
Download is not working If the path starts with `/`

```python
video.download(path='/tmp', quality=phub.Quality.HALF)
```
i've got 
```
Downloading: 100% [206/206]Download failed [Errno 2] No such file or directory: 'tmp/64c3e5c82219e.mp4'
```
the `/` in the begining seems to be ignored

**Comment by Egsagon** [comment]
Yep, my bad. `utils.concat` remove all slashes, including trailling ones. I'll fix this when i find time. In the meantime, you can specify a filename to avoid calling it.

```python
video.download(path=f'/tmp/{video.key}.mp4', quality=phub.Quality.HALF)
```

**Comment by Egsagon** [comment]
Done. Thanks for reporting!
