### ISSUE TITLE
Quality options not working

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#3]
Hi again,

I tried to download a video with the following code:

from phub import Client, Quality

url = "https://de.pornhub.com/view_video.php?viewkey=ph6376413191b91"

client = Client()   # Tested also with client = Client(language="en"), makes no difference
video = client.get("https://de.pornhub.com/view_video.php?viewkey=ph6376413191b91")
title = video.title
video.download(quality=Quality.BEST, quiet=True, path=f"video/{title}.mp4")

But the quality doesn't change, no matter what option I choose. It's always the same file size. In the metadata it says: 854 x 480

I tested it with multiple URLs. I installed the newest version in a virtual environment with: pip install --upgrade git+https://github.com/Egsagon/PHUB.git

In the line 238 in the file utils.py you had a typo misstake: 

        return str(self.vlaue)

I changed it to 
       
        return str(self.value)  

But nothing changed.

**Comment by Egsagon** [comment]
Hi
Fixed with a0c5572fe578014226099e10c82c911b19197033. It was just typos.
Thanks for pointing out!
