### ISSUE TITLE
更新完版本后的错误

### ISSUE THREAD

**Issue by blacktime1999** [Egsagon/PHUB#31]
![image](https://github.com/Egsagon/PHUB/assets/95710926/542e98de-8a26-4ad8-990d-5c1c4a2d07f8)
更新的最新版本，出现这种错误

**Comment by Egsagon** [comment]
There is a new dependency with 4.1.5. See #29.

It should have installed automatically, but if it didn't:
```bash
pip install ffmpeg-progress-yield
```
