### ISSUE TITLE
ERROR: Account already logged in

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#7]
Hey,

I tried to log in with my testing account for my GUI and PHUB constantly raises the "raise consts.AlreadyLoggedIn('Account already connected.')" error. I never had a session before. Even with a VPN it didn't work.  I am not quite sure why. I am using the newest 1.4 version directly from your repo.

Here's a short example code:
```
username = "..."
password = "...."

client = Client(username=username, password=password, language="en")
client.login()
```
(Using delay didn't change anything)

**Comment by Egsagon** [comment]
Hi,

I've changed the way client connects to accounts with [v3.1.2](https://github.com/Egsagon/PHUB/releases/tag/v3.1.2).
For now on, when credentials are passed into a client, it automatically tries to connects to the account, so there is no need to try to connect a second time with `client.login`.
I think its better as most of the time, you instantly want to connect to the account.

To disable this behavior:
```python
client = Client('usr', 'pwd', autologin = False)
```
And then you can use `client.login`.

Have a great day!

**Comment by EchterAlsFake** [comment]
Thanks, your API is the best I've ever used ^^
